version: "3.9"
name: tasks
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_DB: "tasks"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"